import 'package:find_motel/services/motel/models/motels_filter.dart';
import 'package:flutter/material.dart';
import 'package:find_motel/common/models/motel.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class AppDataManager {
  static final AppDataManager _instance = AppDataManager._internal();

  factory AppDataManager() {
    return _instance;
  }

  AppDataManager._internal();

  LatLng? currentLocation;

  MotelsFilter filterMotels = MotelsFilter(
    roomCode: null,
    address: Address(province: 'Tp. Hồ Chí Minh', ward: null),
    amenities: null,
    status: null,
    priceRange: Range2D(values: RangeValues(0, 11), maxValue: 10),
    distanceRange: Range(value: 11, maxValue: 10),
  );

  final List<String> allAmenities = ['Thang máy', 'Xe'];

  final List<RentalStatus> allStatus = RentalStatus.values;

  final List<String> allWardOfTPHCM = [
    'đặc khu Côn Đảo',
    'phường An Đông',
    'phường An Hội Đông',
    'phường An Hội Tây',
    'phường An Khánh',
    'phường An Lạc',
    'phường An Nhơn',
    'phường An Phú',
    'phường An Phú Đông',
    'phường Bàn Cờ',
    'phường Bà Điểm',
    'phường Bà Rịa',
    'phường Bảy Hiền',
    'phường Bến Cát',
    'phường Bến Thành',
    'phường Bình Cơ',
    'phường Bình Chánh',
    'phường Bình Đông',
    'phường Bình Giã',
    'phường Bình Hòa',
    'phường Bình Hưng Hòa',
    'phường Bình Khánh',
    'phường Bình Lợi Trung',
    'phường Bình Phú',
    'phường Bình Quới',
    'phường Bình Tân',
    'phường Bình Thạnh',
    'phường Bình Thới',
    'phường Bình Tiên',
    'phường Bình Trưng',
    'phường Bình Trị Đông',
    'phường Cát Lái',
    'phường Cầu Kiệu',
    'phường Cầu Ông Lãnh',
    'phường Chánh Hiệp',
    'phường Chánh Hưng',
    'phường Chợ Lớn',
    'phường Chợ Quán',
    'phường Dĩ An',
    'phường Diên Hồng',
    'phường Đông Hưng Thuận',
    'phường Đông Hòa',
    'phường Đức Nhuận',
    'phường Gia Định',
    'phường Gò Vấp',
    'phường Hiệp Bình',
    'phường Hòa Bình',
    'phường Hòa Hội',
    'phường Hòa Hưng',
    'phường Hòa Lợi',
    'phường Hạnh Thông',
    'phường Khánh Hội',
    'phường Kim Long',
    'phường Lái Thiêu',
    'phường Linh Xuân',
    'phường Long Bình',
    'phường Long Hải',
    'phường Long Hương',
    'phường Long Nguyên',
    'phường Long Phước',
    'phường Long Trường',
    'phường Minh Phụng',
    'phường Nhiêu Lộc',
    'phường Ngãi Giao',
    'phường Nghĩa Thành',
    'phường Phú An',
    'phường Phú Định',
    'phường Phú Giáo',
    'phường Phú Hóa Đông',
    'phường Phú Lợi',
    'phường Phú Lâm',
    'phường Phú Mỹ',
    'phường Phú Nhuận',
    'phường Phú Thạnh',
    'phường Phú Thọ',
    'phường Phú Thọ Hòa',
    'phường Phú Thuận',
    'phường Phước Hải',
    'phường Phước Long',
    'phường Phước Thắng',
    'phường Rạch Dừa',
    'phường Sài Gòn',
    'phường Sơn Kỳ',
    'phường Tam Bình',
    'phường Tam Long',
    'phường Tam Thắng',
    'phường Tân An Hội',
    'phường Tân Bình',
    'phường Tân Bửu',
    'phường Tân Đông Hiệp',
    'phường Tân Hải',
    'phường Tân Hòa',
    'phường Tân Hưng',
    'phường Tân Khánh',
    'phường Tân Kiểu',
    'phường Tân Mỹ',
    'phường Tân Nhựt',
    'phường Tân Phước',
    'phường Tân Phú',
    'phường Tân Sơn',
    'phường Tân Sơn Hòa',
    'phường Tân Sơn Nhất',
    'phường Tân Sơn Nhì',
    'phường Tân Thành',
    'phường Tân Thạnh',
    'phường Tân Thới Hiệp',
    'phường Tân Thuận',
    'phường Tân Uyên',
    'phường Tân Vĩnh Lộc',
    'phường Tân Vũng Tàu',
    'phường Thạnh Mỹ Tây',
    'phường Thới An',
    'phường Thới Hòa',
    'phường Thông Tây Hội',
    'phường Thủ Dầu Một',
    'phường Thủ Đức',
    'phường Thuận An',
    'phường Thuận Giao',
    'phường Trung Mỹ Tây',
    'phường Vĩnh Hội',
    'phường Vĩnh Tân',
    'phường Vườn Lài',
    'phường Xuân Hòa',
    'phường Xuân Sơn',
    'phường Xuân Thới Sơn',
    'xã An Long',
    'xã An Nhơn Tây',
    'xã An Thới Đông',
    'xã Bắc Tân Uyên',
    'xã Bàu Bàng',
    'xã Bàu Lâm',
    'xã Bình Chánh',
    'xã Bình Giã',
    'xã Bình Hưng',
    'xã Bình Khánh',
    'xã Bình Mỹ',
    'xã Châu Đức',
    'xã Châu Pha',
    'xã Cần Giờ',
    'xã Củ Chi',
    'xã Đất Đỏ',
    'xã Đông Thạnh',
    'xã Hóc Môn',
    'xã Hiệp Phước',
    'xã Hồ Tràm',
    'xã Hòa Hội',
    'xã Hưng Long',
    'xã Kim Long',
    'xã Long Điền',
    'xã Long Hòa',
    'xã Minh Thạnh',
    'xã Nghĩa Thành',
    'xã Nhà Bè',
    'xã Nhuận Đức',
    'xã Phước Hòa',
    'xã Phước Thành',
    'xã Phú Hòa Đông',
    'xã Thái Mỹ',
    'xã Thường Tân',
    'xã Trừ Văn Thố',
    'xã Vĩnh Lộc',
    'xã Xuyên Mộc',
    'xã Xuân Sơn',
  ];
}
