// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBM9Fpyxv841ozwT-ZRCJfgawYUnhgq9A',
    appId: '1:689449733513:web:4ea3664da754ddb9ad2558',
    messagingSenderId: '689449733513',
    projectId: 'findmotel-299a5',
    authDomain: 'findmotel-299a5.firebaseapp.com',
    storageBucket: 'findmotel-299a5.firebasestorage.app',
    measurementId: 'G-PM4XRJ0QX9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUah25f4-i6i3wdK8LUqJ65S8Zk69zRI',
    appId: '1:689449733513:ios:7e0bd6dc4be3530ead2558',
    messagingSenderId: '689449733513',
    projectId: 'findmotel-299a5',
    storageBucket: 'findmotel-299a5.firebasestorage.app',
    iosBundleId: 'com.example.findMotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBM9Fpyxv841ozwT-ZRCJfgawYUnhgq9A',
    appId: '1:689449733513:web:2ff8a679b28c4065ad2558',
    messagingSenderId: '689449733513',
    projectId: 'findmotel-299a5',
    authDomain: 'findmotel-299a5.firebaseapp.com',
    storageBucket: 'findmotel-299a5.firebasestorage.app',
    measurementId: 'G-E3ZCC4S89D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUah25f4-i6i3wdK8LUqJ65S8Zk69zRI',
    appId: '1:689449733513:ios:7e0bd6dc4be3530ead2558',
    messagingSenderId: '689449733513',
    projectId: 'findmotel-299a5',
    storageBucket: 'findmotel-299a5.firebasestorage.app',
    iosBundleId: 'com.example.findMotel',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAniiJDintbsi75Xdqzmfjaj2ASjxcurPw',
    appId: '1:689449733513:android:e1a64b23632f626dad2558',
    messagingSenderId: '689449733513',
    projectId: 'findmotel-299a5',
    storageBucket: 'findmotel-299a5.firebasestorage.app',
  );

}